# basic options
title: Yu Xiang Homepage
author: Yu Xiang
email: shawnxiangyu@yahoo.com
description: "A wonderful site about awesome blogging"

{% include index.html %}


# Build settings
markdown: kramdown
theme: minima
