# basic options
title: Awesome Blog
author: Cool Dude
email: your-email@domain.com
description: "A wonderful site about awesome blogging"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
